version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - DEBUG=true
      - LOG_LEVEL=debug
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=fibrauser
      - DB_PASSWORD=fibrapassword
      - DB_NAME=fibradb
    volumes:
      - .:/srv
      - ./.air.toml:/srv/.air.toml
      - backend-go-cache:/go/pkg/mod
      - ./config:/srv/config
      - backend-data:/srv/data
    networks:
      - fibra-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health || exit 0",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: fibrauser
      POSTGRES_PASSWORD: fibrapassword
      POSTGRES_DB: fibradb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fibra-network

volumes:
  backend-data:
  backend-go-cache:
  pgdata:

networks:
  fibra-network:
    driver: bridge
